### ISSUE TITLE
reproduction of paper results

### ISSUE THREAD

**Issue by kassuts** [shivam-agarwal-17/Keras-training-tools#1]
Hi Shivam, great work with the port, thank you.

I wanted to know if you have any examples of using this code, more specifically if you have tried reproducing the results obtained by Leslie Smith?

[Super-Convergence: Very Fast Training of Neural Networks Using Large Learning Rates
](https://arxiv.org/abs/1708.07120)

**Comment by shivam-agarwal-17** [comment]
Hi, thanks!

No, I ave not reproduced results from the paper by Leslie Smith.
